# The ID of the dataset you created above.
dataset: fast-apply-train

text_completion:
  # How the fields of the JSON dataset should be formatted into the input text.
  # input_template: "### GIVEN THE CONTEXT: {context}  ### INSTRUCTION: {instruction}  ### RESPONSE IS: "
  input_template: "{context}\n{instruction}\n"

  # How the fields of the JSON dataset should be formatted into the output text.
  output_template: "{response}"

# The Fireworks model name of the base model.
# base_model: accounts/fireworks/models/llama-v3p1-8b-instruct
# base_model: accounts/fireworks/models/llama-v3p2-3b-instruct
base_model: accounts/fireworks/models/llama-v3p1-70b-instruct

